const countries = [
  {code:'KE', name:'Kenya', law:'Laws of Kenya', ipOffice:'KIPI (kipi.go.ke)', patentFee:'KES 1,000-5,000', trademarkFee:'KES 5,000-10,000', currency:'KES', region:'Africa'},
  {code:'US', name:'United States', law:'State of Delaware', ipOffice:'USPTO (uspto.gov)', patentFee:'$65-200', trademarkFee:'$250-350', currency:'USD', region:'Americas'},
  {code:'GB', name:'United Kingdom', law:'England and Wales', ipOffice:'UKIPO (gov.uk/ipo)', patentFee:'£60-150', trademarkFee:'£170-200', currency:'GBP', region:'Europe'},
  {code:'IN', name:'India', law:'Republic of India', ipOffice:'CGPDTM (ipindia.gov.in)', patentFee:'₹1,600-8,000', trademarkFee:'₹4,500-9,000', currency:'INR', region:'Asia'},
  {code:'NG', name:'Nigeria', law:'Federal Republic of Nigeria', ipOffice:'NOTAP (notap.gov.ng)', patentFee:'₦10,000-50,000', trademarkFee:'₦20,000-75,000', currency:'NGN', region:'Africa'},
  {code:'ZA', name:'South Africa', law:'Republic of South Africa', ipOffice:'CIPC (cipc.co.za)', patentFee:'R 200-590', trademarkFee:'R 590-3,900', currency:'ZAR', region:'Africa'},
  {code:'EU', name:'European Union', law:'EU Regulations', ipOffice:'EUIPO (euipo.europa.eu)', patentFee:'€100-500', trademarkFee:'€850-1,000', currency:'EUR', region:'Europe'},
  {code:'CN', name:'China', law:'PRC Laws', ipOffice:'CNIPA (cnipa.gov.cn)', patentFee:'¥500-5,000', trademarkFee:'¥300-800', currency:'CNY', region:'Asia'},
  {code:'BR', name:'Brazil', law:'Federative Republic of Brazil', ipOffice:'INPI (gov.br/inpi)', patentFee:'R\$70-350', trademarkFee:'R\$142-355', currency:'BRL', region:'Americas'},
  {code:'RW', name:'Rwanda', law:'Republic of Rwanda', ipOffice:'RDB (rdb.rw)', patentFee:'RWF 10,000-50,000', trademarkFee:'RWF 20,000-80,000', currency:'RWF', region:'Africa'},
  {code:'TZ', name:'Tanzania', law:'United Republic of Tanzania', ipOffice:'BRELA (brela.go.tz)', patentFee:'TZS 50,000-200,000', trademarkFee:'TZS 100,000-300,000', currency:'TZS', region:'Africa'},
  {code:'UG', name:'Uganda', law:'Republic of Uganda', ipOffice:'URSB (ursb.go.ug)', patentFee:'UGX 50,000-200,000', trademarkFee:'UGX 100,000-300,000', currency:'UGX', region:'Africa'},
  {code:'GH', name:'Ghana', law:'Republic of Ghana', ipOffice:'ARIPO (aripo.org)', patentFee:'GHS 200-1,000', trademarkFee:'GHS 500-2,000', currency:'GHS', region:'Africa'},
  {code:'ET', name:'Ethiopia', law:'Federal Democratic Republic of Ethiopia', ipOffice:'EIPO (eipo.gov.et)', patentFee:'ETB 1,000-5,000', trademarkFee:'ETB 2,000-10,000', currency:'ETB', region:'Africa'},
  {code:'JP', name:'Japan', law:'Laws of Japan', ipOffice:'JPO (jpo.go.jp)', patentFee:'¥5,000-20,000', trademarkFee:'¥12,000-38,000', currency:'JPY', region:'Asia'},
  {code:'KR', name:'South Korea', law:'Laws of Republic of Korea', ipOffice:'KIPO (kipo.go.kr)', patentFee:'₩30,000-500,000', trademarkFee:'₩60,000-200,000', currency:'KRW', region:'Asia'},
  {code:'AU', name:'Australia', law:'Commonwealth of Australia', ipOffice:'IP Australia (ipaustralia.gov.au)', patentFee:'AUD 100-500', trademarkFee:'AUD 250-400', currency:'AUD', region:'Oceania'},
  {code:'CA', name:'Canada', law:'Province of Ontario', ipOffice:'CIPO (cipo.ic.gc.ca)', patentFee:'CAD 200-800', trademarkFee:'CAD 250-450', currency:'CAD', region:'Americas'},
  {code:'MX', name:'Mexico', law:'United Mexican States', ipOffice:'IMPI (gob.mx/impi)', patentFee:'MXN 1,000-5,000', trademarkFee:'MXN 2,000-7,000', currency:'MXN', region:'Americas'},
  {code:'AE', name:'UAE', law:'Laws of UAE', ipOffice:'MOEC (moec.gov.ae)', patentFee:'AED 1,000-5,000', trademarkFee:'AED 5,000-10,000', currency:'AED', region:'Middle East'},
  {code:'IL', name:'Israel', law:'State of Israel', ipOffice:'ILPO (justice.gov.il)', patentFee:'₪500-2,000', trademarkFee:'₪1,000-3,000', currency:'ILS', region:'Middle East'},
  {code:'PH', name:'Philippines', law:'Republic of the Philippines', ipOffice:'IPOPHL (ipophil.gov.ph)', patentFee:'₱1,000-5,000', trademarkFee:'₱2,000-8,000', currency:'PHP', region:'Asia'},
  {code:'BD', name:'Bangladesh', law:'People\'s Republic of Bangladesh', ipOffice:'DPDT (dpdt.gov.bd)', patentFee:'৳2,000-10,000', trademarkFee:'৳5,000-15,000', currency:'BDT', region:'Asia'},
]
export default countries
