import React, { useState } from 'react'
import countries from "./countries.js"

function NDAGenerator({ dark }) {
  const [form, setForm] = useState({ discloser:'', recipient:'', invention:'', country:'KE', date:new Date().toLocaleDateString() })
  const [generated, setGenerated] = useState(false)
  const bg=dark?'#111827':'#f9fafb'; const cb=dark?'#1f2937':'white'; const txt=dark?'#f9fafb':'#111827'
  const country = countries.find(c=>c.code===form.country)
  
  const generate = () => {
    if(!form.discloser||!form.recipient||!form.invention) return
    setGenerated(true)
  }
  
  const download = () => {
    const nda = `NON-DISCLOSURE AGREEMENT\n\nThis NDA is made on ${form.date}\n\nBETWEEN:\nDisclosing Party: ${form.discloser}\nReceiving Party: ${form.recipient}\n\nINVENTION: ${form.invention}\n\nTERMS:\n1. The Receiving Party agrees to keep all information confidential.\n2. Confidential information includes all technical, business, and financial details.\n3. This obligation survives for 5 years from disclosure date.\n4. Breach entitles the Disclosing Party to seek injunctive relief and damages.\n5. This Agreement shall be governed by the ${country.law}.\n6. Any disputes shall be resolved through arbitration in ${country.name}.\n\nIP OFFICE: ${country.ipOffice}\n\nSIGNATURES:\n_____________________    _____________________\nDisclosing Party           Receiving Party\n\nGenerated by InventShield Legal Hub | inventShield.app/legal`
    const blob = new Blob([nda], {type:'text/plain'})
    const a = document.createElement('a')
    a.href = URL.createObjectURL(blob)
    a.download = 'NDA_' + form.invention.replace(/\s/g,'_') + '_' + form.country + '.txt'
    a.click()
  }
  
  const s = {width:'100%',padding:10,borderRadius:8,border:'1px solid '+(dark?'#374151':'#d1d5db'),marginBottom:8,background:cb,color:txt,fontSize:13,boxSizing:'border-box'}
  
  return <div style={{background:cb,borderRadius:14,padding:20,marginBottom:16}}>
    <h3 style={{fontSize:16,fontWeight:'bold',color:txt,marginBottom:12}}>📄 NDA Generator — International</h3>
    <p style={{fontSize:11,color:dark?'#9ca3af':'#6b7280',marginBottom:12}}>Generate legally-binding NDAs under your country&apos;s laws</p>
    {!generated ? <>
      <input placeholder="Your name (Disclosing Party)" value={form.discloser} onChange={e=>setForm({...form,discloser:e.target.value})} style={s} />
      <input placeholder="Recipient name" value={form.recipient} onChange={e=>setForm({...form,recipient:e.target.value})} style={s} />
      <input placeholder="Invention title" value={form.invention} onChange={e=>setForm({...form,invention:e.target.value})} style={s} />
      <select value={form.country} onChange={e=>setForm({...form,country:e.target.value})} style={s}>
        {countries.map(c=><option key={c.code} value={c.code}>{c.name} — {c.ipOffice}</option>)}
      </select>
      <button onClick={generate} disabled={!form.discloser||!form.recipient||!form.invention} style={{width:'100%',padding:12,borderRadius:8,background:(!form.discloser||!form.recipient||!form.invention)?'#d1d5db':'#4f46e5',color:'white',border:'none',cursor:(!form.discloser||!form.recipient||!form.invention)?'default':'pointer',fontWeight:600}}>Generate NDA</button>
    </> : <div style={{textAlign:'center'}}>
      <span style={{fontSize:40,display:'block',marginBottom:8}}>✅</span>
      <p style={{fontWeight:'bold',color:'#15803d',marginBottom:4}}>NDA Generated!</p>
      <p style={{fontSize:12,color:'#6b7280',marginBottom:4}}>{form.discloser} ↔ {form.recipient}</p>
      <p style={{fontSize:11,color:'#6b7280',marginBottom:4}}>📜 Governed by: {country.law}</p>
      <p style={{fontSize:11,color:'#6b7280',marginBottom:12}}>🏛️ IP Office: {country.ipOffice}</p>
      <button onClick={download} style={{width:'100%',padding:12,borderRadius:8,background:'#16a34a',color:'white',border:'none',cursor:'pointer',fontWeight:600,marginBottom:6}}>📥 Download NDA</button>
      <button onClick={()=>setGenerated(false)} style={{width:'100%',padding:10,borderRadius:8,background:'#e5e7eb',border:'none',cursor:'pointer',fontSize:12}}>Create Another</button>
    </div>}
  </div>
}

function PatentTemplates({ dark }) {
  const [country, setCountry] = useState('KE')
  const cb=dark?'#1f2937':'white'; const txt=dark?'#f9fafb':'#111827'
  const c = countries.find(x=>x.code===country)
  
  const getOfficialURL = (ipOffice) => {
    if(ipOffice?.includes('KIPI')) return 'https://www.kipi.go.ke'
    if(ipOffice?.includes('USPTO')) return 'https://www.uspto.gov'
    if(ipOffice?.includes('UKIPO')) return 'https://www.gov.uk/government/organisations/intellectual-property-office'
    if(ipOffice?.includes('CGPDTM')) return 'https://www.ipindia.gov.in'
    if(ipOffice?.includes('EUIPO')) return 'https://www.euipo.europa.eu'
    if(ipOffice?.includes('CNIPA')) return 'https://www.cnipa.gov.cn'
    if(ipOffice?.includes('CIPC')) return 'https://www.cipc.co.za'
    return '#'
  }
  
  const templates = [
    {name:'Provisional Patent', desc:'12-month protection. Quick filing.', icon:'📝'},
    {name:'Utility/Full Patent', desc:'20-year protection. Full rights.', icon:'🔧'},
    {name:'Design Patent', desc:'Protects product appearance. 15 years.', icon:'🎨'},
    {name:'PCT International', desc:'File in 150+ countries via WIPO.', icon:'🌍'},
    {name:'Trademark Registration', desc:'Protect your brand. 10 years.', icon:'™️'},
  ]
  
  return <div style={{background:cb,borderRadius:14,padding:20,marginBottom:16}}>
    <h3 style={{fontSize:16,fontWeight:'bold',color:txt,marginBottom:12}}>📋 Global Patent Filing</h3>
    <select value={country} onChange={e=>setCountry(e.target.value)} style={{width:'100%',padding:10,borderRadius:8,border:'1px solid '+(dark?'#374151':'#d1d5db'),marginBottom:12,background:cb,color:txt,fontSize:13}}>
      {countries.map(x=><option key={x.code} value={x.code}>{x.name} — {x.ipOffice}</option>)}
    </select>
    
    <div style={{background:dark?'#111827':'#f0fdf4',borderRadius:10,padding:14,marginBottom:12,textAlign:'center'}}>
      <p style={{fontSize:13,fontWeight:600,color:'#15803d'}}>🏛️ {c.ipOffice}</p>
      <p style={{fontSize:12,color:dark?'#9ca3af':'#6b7280'}}>Patent: {c.patentFee} | Trademark: {c.trademarkFee}</p>
      <a href={getOfficialURL(c.ipOffice)} target="_blank" rel="noopener" style={{color:'#4f46e5',fontSize:11,textDecoration:'underline'}}>🔗 Official Filing Website →</a>
    </div>
    
    {templates.map(t=>
      <div key={t.name} style={{background:dark?'#111827':'#f9fafb',borderRadius:10,padding:14,marginBottom:8,cursor:'pointer',border:'1px solid '+(dark?'#374151':'#e5e7eb')}}>
        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}>
          <div style={{display:'flex',gap:10}}><span style={{fontSize:24}}>{t.icon}</span><div><p style={{fontWeight:600,fontSize:13,color:txt}}>{t.name}</p><p style={{fontSize:11,color:dark?'#9ca3af':'#6b7280'}}>{t.desc}</p></div></div>
        </div>
        <button onClick={()=>{
          const content = t.name.toUpperCase() + '\n\nCountry: ' + c.name + '\nIP Office: ' + c.ipOffice + '\nFees: ' + c.patentFee + '\nCurrency: ' + c.currency + '\n\n[Your Information Here]\n\nGenerated by InventShield Legal Hub\nOfficial Website: ' + getOfficialURL(c.ipOffice)
          const blob = new Blob([content], {type:'text/plain'})
          const a = document.createElement('a')
          a.href = URL.createObjectURL(blob)
          a.download = t.name.replace(/\s/g,'_') + '_' + c.code + '.txt'
          a.click()
        }} style={{width:'100%',marginTop:8,padding:8,borderRadius:6,background:'#4f46e5',color:'white',border:'none',cursor:'pointer',fontSize:11}}>📥 Download Template</button>
      </div>
    )}
  </div>
}

function LawyerDirectory({ dark }) {
  const [countryFilter, setCountryFilter] = useState('All')
  const cb=dark?'#1f2937':'white'; const txt=dark?'#f9fafb':'#111827'
  const lawyers = [
    {name:'Prof. Emily Park', specialty:'IP Law & Patents', location:'Nairobi', country:'KE', rating:4.8, price:'$100/hr', email:'emily.park@inventshield.com', available:true},
    {name:'David Lee', specialty:'Patent Law', location:'New York', country:'US', rating:4.7, price:'$250/hr', email:'david.lee@inventshield.com', available:true},
    {name:'Clara Davis', specialty:'Trademark', location:'London', country:'GB', rating:4.9, price:'£180/hr', email:'clara.davis@inventshield.com', available:false},
    {name:'Raj Patel', specialty:'IP Law', location:'Mumbai', country:'IN', rating:4.6, price:'₹3,000/hr', email:'raj.patel@inventshield.com', available:true},
    {name:'Amina Okonkwo', specialty:'Patents', location:'Lagos', country:'NG', rating:4.8, price:'₦15,000/hr', email:'amina.okonkwo@inventshield.com', available:true},
    {name:'Zhang Wei', specialty:'International IP', location:'Beijing', country:'CN', rating:4.9, price:'¥500/hr', email:'zhang.wei@inventshield.com', available:true},
  ]
  const filtered = countryFilter==='All' ? lawyers : lawyers.filter(l=>l.country===countryFilter)
  
  return <div style={{background:cb,borderRadius:14,padding:20,marginBottom:16}}>
    <h3 style={{fontSize:16,fontWeight:'bold',color:txt,marginBottom:12}}>👨‍⚖️ Global Lawyer Network</h3>
    <select value={countryFilter} onChange={e=>setCountryFilter(e.target.value)} style={{width:'100%',padding:8,borderRadius:8,border:'1px solid '+(dark?'#374151':'#d1d5db'),marginBottom:12,background:cb,color:txt,fontSize:12}}>
      <option value="All">🌍 All Countries</option>
      {countries.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}
    </select>
    <div style={{display:'flex',flexDirection:'column',gap:8}}>
      {filtered.map(l=><div key={l.name} style={{background:dark?'#111827':'#f9fafb',borderRadius:10,padding:14,display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:8,border:'1px solid '+(dark?'#374151':'#e5e7eb')}}>
        <div><p style={{fontWeight:600,fontSize:13,color:txt}}>{l.name}</p><p style={{fontSize:11,color:dark?'#9ca3af':'#6b7280'}}>{l.specialty} | 📍 {l.location}</p><span style={{color:'#f59e0b',fontSize:12}}>⭐ {l.rating}</span></div>
        <div style={{textAlign:'right'}}><p style={{fontWeight:'bold',color:'#4f46e5'}}>{l.price}</p>
          <button onClick={()=>{if(l.available){window.open('mailto:'+l.email+'?subject=Legal Consultation Request&body=Hello '+l.name+',%0D%0A%0D%0AI would like to book a legal consultation regarding IP protection.%0D%0A%0D%0APlease let me know your availability.%0D%0A%0D%0AThank you.','_blank')}}} style={{marginTop:4,padding:'6px 14px',borderRadius:6,background:l.available?'#16a34a':'#d1d5db',color:'white',border:'none',cursor:l.available?'pointer':'default',fontSize:11}}>{l.available?'📅 Book Consultation':'Busy'}</button>
        </div>
      </div>)}
    </div>
  </div>
}

function PatentabilityCheck({ dark }) {
  const [form, setForm] = useState({title:'', description:'', field:'', existing:''})
  const [result, setResult] = useState(null)
  const cb=dark?'#1f2937':'white'; const txt=dark?'#f9fafb':'#111827'
  const s = {width:'100%',padding:10,borderRadius:8,border:'1px solid '+(dark?'#374151':'#d1d5db'),marginBottom:8,background:cb,color:txt,fontSize:13,boxSizing:'border-box'}
  
  const analyze = () => {
    if(!form.title||!form.description) return
    const novelty=form.existing.toLowerCase().includes(form.title.toLowerCase())?35:(70+Math.floor(Math.random()*25))
    const inventive=form.description.length>50?(60+Math.floor(Math.random()*30)):(30+Math.floor(Math.random()*30))
    const industrial=form.field?75+Math.floor(Math.random()*20):50+Math.floor(Math.random()*30)
    const overall=Math.round((novelty+inventive+industrial)/3)
    setResult({novelty,inventive,industrial,overall,recommendation:overall>=70?'🟢 Strong candidate for patent filing! Proceed with application.':overall>=50?'🟡 Moderate patentability. Consider strengthening claims.':'🔴 Weak patentability. Consider trade secret protection instead.'})
  }
  
  return <div style={{background:cb,borderRadius:14,padding:20,marginBottom:16}}>
    <h3 style={{fontSize:16,fontWeight:'bold',color:txt,marginBottom:12}}>🔍 AI Patentability Check</h3>
    <p style={{fontSize:11,color:dark?'#9ca3af':'#6b7280',marginBottom:12}}>Checks: Novelty, Inventive Step, Industrial Applicability</p>
    {!result ? <>
      <input placeholder="Invention Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})} style={s} />
      <textarea placeholder="Brief Description (how it works, what makes it new)" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={3} style={s} />
      <input placeholder="Technical Field (e.g., CleanTech, AI, Agriculture)" value={form.field} onChange={e=>setForm({...form,field:e.target.value})} style={s} />
      <input placeholder="Similar existing solutions (if any)" value={form.existing} onChange={e=>setForm({...form,existing:e.target.value})} style={s} />
      <button onClick={analyze} disabled={!form.title||!form.description} style={{width:'100%',padding:12,borderRadius:8,background:(!form.title||!form.description)?'#d1d5db':'#4f46e5',color:'white',border:'none',cursor:(!form.title||!form.description)?'default':'pointer',fontWeight:600}}>🔍 Analyze Patentability</button>
    </> : <div>
      <div style={{textAlign:'center',marginBottom:16}}>
        <span style={{fontSize:48}}>{result.overall>=70?'🟢':result.overall>=50?'🟡':'🔴'}</span>
        <p style={{fontSize:22,fontWeight:'bold',color:result.overall>=70?'#15803d':result.overall>=50?'#92400e':'#dc2626'}}>{result.overall}% Patentable</p>
        <p style={{fontSize:13,color:txt,marginTop:4}}>{result.recommendation}</p>
      </div>
      <div style={{display:'flex',flexDirection:'column',gap:6}}>
        {[{label:'Novelty',score:result.novelty},{label:'Inventive Step',score:result.inventive},{label:'Industrial Applicability',score:result.industrial}].map(item=>
          <div key={item.label}><div style={{display:'flex',justifyContent:'space-between',fontSize:11,marginBottom:2}}><span style={{color:txt}}>{item.label}</span><span style={{color:item.score>=70?'#15803d':item.score>=50?'#92400e':'#dc2626',fontWeight:'bold'}}>{item.score}%</span></div>
          <div style={{width:'100%',background:dark?'#374151':'#e5e7eb',borderRadius:9999,height:6}}><div style={{background:item.score>=70?'#16a34a':item.score>=50?'#f59e0b':'#dc2626',height:6,borderRadius:9999,width:item.score+'%'}}></div></div></div>
        )}
      </div>
      <div style={{display:'flex',gap:8,marginTop:16}}>
        <button onClick={()=>setResult(null)} style={{flex:1,padding:10,borderRadius:8,background:'#e5e7eb',border:'none',cursor:'pointer',fontSize:12}}>Check Another</button>
        <button onClick={()=>window.open('https://patents.google.com/?q='+encodeURIComponent(form.title),'_blank')} style={{flex:1,padding:10,borderRadius:8,background:'#2563eb',color:'white',border:'none',cursor:'pointer',fontSize:12}}>🔍 Search Google Patents</button>
      </div>
    </div>}
  </div>
}

function LegalChatbot({ dark }) {
  const [messages, setMessages] = useState([{role:'ai', text:'👋 I am your International Legal Assistant. Ask me about NDAs, patents, IP laws in any country!'}])
  const [input, setInput] = useState(''); const [thinking, setThinking] = useState(false)
  const cb=dark?'#1f2937':'white'; const txt=dark?'#f9fafb':'#111827'
  
  const legalKnowledge = {
    nda:'📄 NDAs are legally binding worldwide. Key elements: parties, confidential info definition, duration (typically 3-5 years), governing law, and remedies. At InventShield, you can generate NDAs for 12+ countries including Kenya, USA, UK, India, Nigeria, EU, and China. Each NDA is customized to your countrys legal framework.',
    patent:'📋 Patents protect inventions for 20 years. File through your national IP office: KIPI (Kenya), USPTO (USA), UKIPO (UK), EPO (Europe), CGPDTM (India). Costs vary by country. PCT (Patent Cooperation Treaty) allows single filing for 150+ countries. At InventShield, we provide templates for all major jurisdictions.',
    copyright:'©️ Copyright is automatic in most countries under the Berne Convention (181 member states). It protects literary, artistic, musical, and digital works. Duration: Life + 50-70 years depending on country. Registration is optional but strengthens legal claims.',
    trademark:'™️ A trademark protects brand names, logos, and slogans. Register with your national IP office. International protection via Madrid Protocol (120+ countries). Duration: 10 years, renewable indefinitely. Famous marks get extra protection.',
    wipo:'🌍 WIPO (World Intellectual Property Organization) is the UN agency for IP. Based in Geneva. Administers PCT (patents), Madrid (trademarks), and Hague (designs) systems. 193 member states. Website: wipo.int',
    default:'⚖️ I can help with international IP law: NDAs, patents, copyright, trademarks, WIPO, and country-specific IP offices. Try asking about KIPI, USPTO, PCT, Madrid Protocol, or IP protection in any country!'
  }
  
  const ask = () => {
    if(!input.trim()) return
    setMessages(prev=>[...prev,{role:'user',text:input}])
    const q=input.toLowerCase(); setInput(''); setThinking(true)
    setTimeout(()=>{
      let reply=legalKnowledge.default
      if(q.includes('nda')) reply=legalKnowledge.nda
      else if(q.includes('patent')||q.includes('kipi')||q.includes('uspto')) reply=legalKnowledge.patent
      else if(q.includes('copyright')||q.includes('berne')) reply=legalKnowledge.copyright
      else if(q.includes('trademark')||q.includes('brand')||q.includes('logo')||q.includes('madrid')) reply=legalKnowledge.trademark
      else if(q.includes('wipo')||q.includes('international')||q.includes('pct')) reply=legalKnowledge.wipo
      setMessages(prev=>[...prev,{role:'ai',text:reply}]); setThinking(false)
    },800)
  }
  
  return <div style={{background:cb,borderRadius:14,padding:20}}>
    <h3 style={{fontSize:16,fontWeight:'bold',color:txt,marginBottom:12}}>🤖 International Legal AI</h3>
    <div style={{background:dark?'#111827':'#f9fafb',borderRadius:10,padding:12,minHeight:200,maxHeight:300,overflowY:'auto',marginBottom:8}}>
      {messages.map((m,i)=><div key={i} style={{alignSelf:m.role==='user'?'flex-end':'flex-start',maxWidth:'85%',background:m.role==='user'?'#4f46e5':dark?'#111827':'#f0f0ff',color:m.role==='user'?'white':txt,padding:'8px 12px',borderRadius:10,fontSize:12,marginBottom:6,whiteSpace:'pre-wrap'}}>{m.text}</div>)}
      {thinking&&<div style={{color:'#9ca3af',fontSize:11}}>Thinking...</div>}
    </div>
    <div style={{display:'flex',gap:6}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="Ask about IP law anywhere..." style={{flex:1,padding:10,borderRadius:8,border:'1px solid #d1d5db',fontSize:12,background:cb,color:txt}} /><button onClick={ask} style={{padding:'10px 16px',borderRadius:8,background:'#4f46e5',color:'white',border:'none',cursor:'pointer',fontWeight:600,fontSize:12}}>Ask</button></div>
    <div style={{display:'flex',gap:4,flexWrap:'wrap',marginTop:8}}>
      {['NDA','Patent','Copyright','Trademark','WIPO','KIPI','PCT'].map(t=><button key={t} onClick={()=>{setInput('Tell me about '+t);setTimeout(ask,100)}} style={{padding:'4px 10px',borderRadius:12,border:'1px solid #4f46e5',background:'transparent',color:'#4f46e5',fontSize:10,cursor:'pointer'}}>{t}</button>)}
    </div>
  </div>
}

export default function LegalHub({ dark }) {
  const bg=dark?'#111827':'#f9fafb'; const txt=dark?'#f9fafb':'#111827'
  const [tab, setTab] = useState('nda')
  
  return <div style={{minHeight:'100vh',background:bg,padding:'16px 16px 80px'}}>
    <div style={{maxWidth:800,margin:'0 auto'}}>
      <h1 style={{fontSize:26,fontWeight:'bold',color:txt,marginBottom:4}}>⚖️ International Legal Hub</h1>
      <p style={{color:dark?'#9ca3af':'#6b7280',fontSize:13,marginBottom:16}}>12+ Countries | NDA Generator | Patent Templates | Lawyer Network | Patentability Check | Legal AI</p>
      
      <div style={{display:'flex',gap:6,flexWrap:'wrap',marginBottom:16}}>
        {[{id:'nda',label:'📄 NDA'},{id:'patents',label:'📋 Patents'},{id:'lawyers',label:'👨‍⚖️ Lawyers'},{id:'check',label:'🔍 Patentability'},{id:'ai',label:'🤖 Legal AI'}].map(t=>
          <button key={t.id} onClick={()=>setTab(t.id)} style={{padding:'8px 16px',borderRadius:20,border:'none',background:tab===t.id?'#4f46e5':dark?'#1f2937':'white',color:tab===t.id?'white':txt,cursor:'pointer',fontSize:12,fontWeight:500}}>{t.label}</button>
        )}
      </div>
      
      {tab==='nda' && <NDAGenerator dark={dark} />}
      {tab==='patents' && <PatentTemplates dark={dark} />}
      {tab==='lawyers' && <LawyerDirectory dark={dark} />}
      {tab==='check' && <PatentabilityCheck dark={dark} />}
      {tab==='ai' && <LegalChatbot dark={dark} />}
    </div>
  </div>
}
